<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ha-desklink</AssemblyName>
    <RootNamespace>HaDeskLink</RootNamespace>
    <Version>2.1.1</Version>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="VERSION" CopyToOutputDirectory="PreserveNewst" />
  </ItemGroup>

</Project>