<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ha-desklink</AssemblyName>
    <RootNamespace>HaDeskLink</RootNamespace>
    <Version>3.0.0</Version>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets/icon.ico</ApplicationIcon>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="VERSION" CopyToOutputDirectory="PreserveNewst" />
    <AvaloniaResource Include="Assets/icon.png" />
    <None Include="Lang/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>